name: 'Issue Checker'
description: 'A GitHub Action that labels and comments on issues that are missing required information'
author: 'Steven Zeck'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: true
    default: ${{ github.token }}
  label-name:
    description: 'The name of the label to apply to an issue when it''s missing required information.'
    required: false
    default: 'waiting-for-user-information'
  label-color:
    description: 'Hex format for the color of the label that is applied to an issue (only used if label doesn''t already exist).'
    required: false
    default: 'ffffff'
  comment-text:
    description: 'The text of the comment that is added to an issue.'
    required: false
    default: ''
  check-tasks:
    description: 'Whether or not to check that all tasks are completed.'
    required: false
    default: 'false'
  keywords:
    description: 'A comma delimited list of keywords to look for when an issue is created or edited'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
